--- #YAML:1.0
name:                Weather-Bug
version:             0.24
abstract:            Provide an object oriented interface to the WeatherBug API.
license:             ~
author:              
    - G. Wade Johnson <wade@anomaly.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DateTime:                      0
    DateTime::Format::Builder:     0
    LWP::Simple:                   0
    Moose:                         0
    overload:                      0
    Test::Group:                   0
    Test::More:                    0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
